@startuml
title: Can Read committed Testdata using Service RequiresNew?
actor Test as t
participant service as s
participant "transaction\nmanager" as tm
database db
t -> tm: begin Transaction 1
t -> db: insert testdata
db -> t: return generated ids
t -> tm: commit Transaction 1
t -> tm: start RequiresNew Transaction 2
t -> s: read Data(id)
note right of s:  s will use the\nrunning\ntransaction
s -> db: read by id
note right of db: can read since\ntransaction 1\nis committed
db -> s: data
s -> t: return data
t -> tm: commit transaction 2
t -> t: check
@enduml