package net.oneandone.ejbcdiunit.relbuilder.code;

/**
 * @author aschoerk
 */
public enum RelType {
    ROOT,
    PRODUCER_FIELD,
    PRODUCER_METHOD,
    INJECTED_FIELD,
    INJECTED_PARAMETER,
    ADDED_BEAN,
    ADDED_CLASS,
    ADDED_ANNOTATION,
    SIMPLE_BEAN,
    CONSTRUCTOR_INJECT,
    EXCLUDED_CLASSES_ANNOTATION,
    ADDITIONAL_CLASSES_ANNOTATION,
    ADDITIONAL_PACKAGE_ANNOTATION,
    ADDITIONAL_CLASSPATH_ANNOTATION,
    EJB_CLASSPATH_ANNOTATION,
    ACTIVATED_ALTERNATIVES_ANNOTATION;
}
